Repository digipen-team-uwu/uwu-engine, pull requests merged in 2020-01, with the labels that each got.

#25 finally fixed magic enum submodule for real
  .gitmodules
Labels: pipeline

#34 Timer singleton and system registration fix
  include/UWUEngine/BaseSystem.inline.cpp
  include/UWUEngine/Component/BaseComponent.h
  include/UWUEngine/Engine.h
  include/UWUEngine/SystemUpdater.h
  include/UWUEngine/SystemUpdater.inline.cpp
  include/UWUEngine/Timer.h
  src/EngineCore/Behaviors/HUDBehaviors.cpp
  src/EngineCore/Behaviors/ParticleSystem.cpp
  src/EngineCore/Behaviors/TextObject.cpp
  src/EngineCore/Components/AnimationComponentManager.cpp
  src/EngineCore/Components/BehaviorComponentManager.cpp
  src/EngineCore/Components/ColliderComponentManager.cpp
  src/EngineCore/Components/PhysicsComponentManager.cpp
  src/EngineCore/Components/SpineAnimationComponentManager.cpp
  src/EngineCore/Components/SpineSkeletonComponentManager.cpp
  src/EngineCore/Components/TextureComponentManager.cpp
  src/EngineCore/Debugs/DebugManager.cpp
  src/EngineCore/Debugs/TraceLogger.cpp
  src/EngineCore/Editor/DragAndDrop.cpp
  src/EngineCore/Editor/Editor.cpp
  src/EngineCore/Engine.cpp
  src/EngineCore/Entity/EntityManager.cpp
  src/EngineCore/Entity/EntityVector.cpp
  src/EngineCore/Graphics/Camera.cpp
  src/EngineCore/Graphics/Instances.cpp
  src/EngineCore/Graphics/Lighting/Lighting.cpp
  src/EngineCore/Graphics/Render.cpp
  src/EngineCore/Graphics/Shader/UniformBufferSystem.cpp
  src/EngineCore/Graphics/Texture/TextureAtlaser.cpp
  src/EngineCore/Graphics/Texture/TextureLoader.cpp
  src/EngineCore/Input/ActionManager.cpp
  src/EngineCore/Input/InputManager.cpp
  src/EngineCore/Random.cpp
  src/EngineCore/SoundInterface.cpp
  src/EngineCore/Timer.cpp
  src/EngineCore/UI/HUDManager.cpp
  src/EngineCore/UI/UIManager.cpp
  src/EngineCore/WindowManager.cpp
  src/Executable/GameStateManager.cpp
  src/Executable/Scenes/BrayanSBOX.cpp
  src/Executable/Scenes/Level1.cpp
  src/Executable/Scenes/Level2.cpp
  src/Executable/SystemRegistration.cpp
Labels: bug, pipeline

#37 Event System & Collision detection refactor
  CMakeLists.txt
  include/UWUEngine/Behaviors/ParticleSystem.h
  include/UWUEngine/Component/BaseComponent.h
  include/UWUEngine/Component/ColliderComponentManager.h
  include/UWUEngine/Event/Event.h
  include/UWUEngine/Event/EventDispatcher.h
  include/UWUEngine/Event/EventListener.h
  include/UWUEngine/Event/EventType.h
  include/UWUEngine/Event/Type/Collision.h
  include/UWUEngine/FrameRateController.h
  include/UWUEngine/GamePlay/FangBehavior.h
  include/UWUEngine/GamePlay/PerceptionBehavior.h
  include/UWUEngine/GamePlay/PlayerController.h
  include/UWUEngine/Helper.h
  include/UWUEngine/Physics/Colliders/Collider.h
  include/UWUEngine/Physics/Colliders/ColliderPolygon.h
  include/UWUEngine/SystemOrder.h
  src/EngineCore/Behaviors/HUDBehaviors.cpp
  src/EngineCore/Components/ColliderComponentManager.cpp
  src/EngineCore/Components/TransformComponentManager.cpp
  src/EngineCore/Debugs/DebugManager.cpp
  src/EngineCore/Debugs/TraceLogger.cpp
  src/EngineCore/Editor/EditorMainMenu.cpp
  src/EngineCore/Entity/EntityCacher.cpp
  src/EngineCore/Event/Event.cpp
  src/EngineCore/Event/EventDispatcher.cpp
  src/EngineCore/Event/EventListener.cpp
  src/EngineCore/Event/Type/Collision.cpp
  src/EngineCore/FrameRateController.cpp
  src/EngineCore/GamePlay/Enemy/Fang/FangBehavior.cpp
  src/EngineCore/GamePlay/Enemy/Perception/PerceptionAttack.cpp
  src/EngineCore/GamePlay/Enemy/Perception/PerceptionBehavior.cpp
  src/EngineCore/GamePlay/Enemy/Perception/PerceptionIdle.cpp
  src/EngineCore/GamePlay/Player/PlayerAirborne.cpp
  src/EngineCore/GamePlay/Player/PlayerController.cpp
  src/EngineCore/GamePlay/Player/PlayerDash.cpp
  src/EngineCore/GamePlay/Player/PlayerGrounded.cpp
  src/EngineCore/Graphics/Camera.cpp
  src/EngineCore/Physics/Colliders/Collider.cpp
  src/EngineCore/Physics/Colliders/ColliderPolygon.cpp
  src/EngineCore/Serialization.cpp
  src/Executable/SystemRegistration.cpp
Labels: enhancement
